routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('gestion', 'GestionController');

Route::get('/gestiones','GestionClienteController@index')->name('gestiones');
Route::post('/gestion/add/','GestionClienteController@agregar')->name('gestionAdd');

Route::get('/ticket','TicketController@index')->name('ticket');
Route::post('/ticket/get/{atender?}','TicketController@lista')->name('listado');
Route::post('/ticket/save','TicketController@guardar')->name('guardar');

app/Gestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gestion extends Model
{

    protected $table = 'gestiones';

    protected $fillable = [
        'nombre', 'visita', 'id_user'
    ];
    //
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function gestionCliente(){
        return $this->hasMany(GestionCliente::class,'id_gestion');
    }


}

app/Http/Controllers/GestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Gestion;
use Facade\Ignition\Solutions\GenerateAppKeySolution;
use Illuminate\Support\Facades\Auth;

class GestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = new Gestion();
        return view('gestion.index', [
            'data' => $data->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('gestion.nuevo');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valido = $request->validate([
            'nombre' => 'required|max:255',
        ]);

        $valido['visita'] = empty($request->input('visita')) ? 0 : 1;
        $valido['id_user']  = Auth::id();

        Gestion::create($valido);

        return redirect('/gestion')->with('mensaje', 'Registro almacenado con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $data = Gestion::findOrFail($id);

        return view('gestion.editar', [
            'data' => $data
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $valido = $request->validate([
            'nombre' => 'required|max:255'
        ]);
        $valido['visita'] = empty($request->input('visita')) ? 0 : 1;
        $valido['id_user']  = Auth::id();

        Gestion::whereId($id)->update($valido);
        return redirect('/gestion')->with('mensaje', 'Registro actualizado con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $data = Gestion::findOrFail($id);
        $data->delete();

        return redirect('/gestion')->with('mensaje', 'Registro eliminado');
    }
}

resources/views/gestion/editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="card uper">
        <form method="post" action="{{ route('gestion.update',$data->id) }}">
            <div class="card-header text-center">
                Editar Gestión
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif

                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="nombre">Nombre:</label>
                    <input type="text" name="nombre" class="form-control" required="required"
                    value="{{$data->nombre}}" />
                </div>
                <div class="form-check">
                    <input type="checkbox" name="visita" class="form-check-input" id="visita" value="1"
                    @if( 1==(int)$data->visita)
                    checked
                    @endif
                    >

                    <label class="form-check-label" for="visita">Visita técnica</label>
                </div>

            </div>

            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>

                <a href="{{ route('gestion.index') }}" class="btn btn-danger " role="button">
                    Cancelar
                </a>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/gestion/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="col-md-12 text-center">
        <h3>
            Catálogo de Gestión
        </h3>

        <a href="{{ route('gestion.create') }}" class="btn btn-primary btn-lg " role="button">
            Agregar
        </a>
    </div>
    @if(session()->get('mensaje'))
    <div class="alert alert-success">
        {{ session()->get('mensaje') }}
    </div><br />
    @endif
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Visita técnica</th>
                <th colspan="2">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $fila)
            <tr>
                <td>{{$fila->nombre}}</td>
                <td> {{empty($fila->visita)?'No':'Si'}} </td>
                <td>

                    <a href="{{ route('gestion.edit', $fila->id)}}" class="btn btn-success">
                        Editar
                    </a>

                </td>
                <td>
                    <form action="{{ route('gestion.destroy', $fila->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button type="button" class="btn btn-danger"
                            onclick="return confirmar(this.form)">Eliminar</button>
                    </form>

                </td>
            </tr>
            @endforeach

            @if ($data->count()<=0) <tr>
                <td colspan="3" class="text-center">Níngun registro para mostrar</td>
                </tr>
                @endif
        </tbody>

    </table>

    <div class="justify-content-center">
        {{ $data->links() }}
    </div>
</div>

<script>
    function confirmar(frm){
        if(confirm('¿Desea eliminar el registro?')){
            frm.submit();
        }
    }

</script>

@endsection

resources/views/gestion/nuevo.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="card uper">
        <form method="post" action="{{ route('gestion.store') }}">
            <div class="card-header text-center">
                Agregar Gestión
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
                @endif

                <div class="form-group">
                    @csrf
                    <label for="nombre">Nombre:</label>
                    <input type="text" name="nombre" class="form-control" required="required" autofocus />
                </div>
                <div class="form-check">
                    <input type="checkbox" name="visita" class="form-check-input" id="visita" value="1">
                    <label class="form-check-label" for="visita">Visita técnica</label>
                </div>

            </div>

            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>

                <a href="{{ route('gestion.index') }}" class="btn btn-danger " role="button">
                    Cancelar
                </a>
            </div>
        </form>
    </div>
</div>
@endsection